[build]
  command = "hugo --gc --minify"
  base    = ""
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.60.1"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture"

[context.branch-deploy]
  command = "hugo --gc --minify"

[[headers]]
  for = "*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"

[[headers]]
  for = "index.xml"
  [headers.values]
    Content-Type = "application/rss+xml"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    #Content-Security-Policy = "default-src 'none'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; base-uri 'self';  img-src 'self';  frame-src 'self'; font-src 'self' data:; object-src 'none'; frame-ancestors 'none';"

[[redirects]]
  from = "https://www.sufficientlysecure.org/*"
  to = "https://www.schuermann.eu/:splat"
  status = 301

# custom domain sufficientlysecure.org
[[redirects]]
  from = "https://sufficientlysecure.org"
  to = "https://www.schuermann.eu"
  status = 301

[[redirects]]
  from = "https://www.sufficientlysecure.org"
  to = "https://www.schuermann.eu"
  status = 301
